### ISSUE TITLE
Token hatası

### ISSUE THREAD

**Issue by dizaynbilgi** [ozdemirr/mikro-odeme#1]
Mikro Ödeme' nin en çok kullanılan SaleWithTicket ödeme tipi için örnek Kullanım olarak verdiğiniz kodları denedim ancak 
**"Fatal error: Class 'MikroOdeme\Model\Shared\Token' not found in /home/alanadi/public_html/lib/mobilodeme.php on line 9"** 
hatası alıyorum. 
Onaylanmış başvurumdaki UserCode ve Pin i kullandım.

**Comment by ozdemirr** [comment]
Merhaba, Token Class' ını use ettiğinizden eminmisiniz ?

**Comment by dizaynbilgi** [comment]
Merhaba,
lib klasörü ile birlikte yükledim
başlangıçta use ettiğim dosyalar
use MikroOdeme\Model\Sale\SaleWithTicket;
use MikroOdeme\Model\Shared\Input;
use MikroOdeme\Model\Sale\MSaleProduct;
use MikroOdeme\Model\Shared\Token;
use MikroOdeme\Exception\ConfigurationException;
use MikroOdeme\Exception\MikroOdemeException;

**Comment by ozdemirr** [comment]
composer require "ozdemirr/mikro-odeme:*" komutunu uygularak sdk' yı projenize dahil ettiniz mi ? Autoload işleminde sıkıntı yaşanmış gibi görünüyor.

**Comment by dizaynbilgi** [comment]
include ederek çözemezmiyiz peki ssh a erişim sağlayamıyorum

**Comment by ozdemirr** [comment]
En sağlıklı ve geçerli yol, diğer tüm kürüphanelerde de yapıldığı gibi composer ile yüklemek. Problem sdk' nın kendisinden değil, diğer problemlerden kaynaklandığı için konuyu kapatıyorum, iyi çalışmalar.
