### ISSUE TITLE
Ödeme ekranı açılmıyor

### ISSUE THREAD

**Issue by kodajans** [ozdemirr/mikro-odeme#2]
Merhaba
**$result->SaleWithTicketResult->RedirectUrl;**
 bu bölüm boş olarak dönüyor. O yüzden ödeme ekranı açılmıyor. Sorun kaynağı ne olabilir, teşekkürler

**Comment by ozdemirr** [comment]
sorunun kaynağını, anasayfaki dökümanda gösterildiği gibi, catch block larının içinde hata mesajını dump ederek görebilirsiniz.

**Comment by kodajans** [comment]
**[message:protected] => Server was unable to process request. ---> Object reference not set to an instance of an object.**
verdiği hata bu api dökümantasyonunda hangi api kullanacaksanız integration@3pay.com mail adresinden izin isteyin denmiş bu yüzden olabilir mi

**Comment by ozdemirr** [comment]
3pay ile resmi olarak çalışmıyormusunuz ? Geçerli usercode ve pin' e sahip değilmisiniz ?

**Comment by kodajans** [comment]
evet geçerli pin, usercode ve turkcellid mevcut

**Comment by ozdemirr** [comment]
SDK az önce tekrar test edildi. 3PAY' in api sinde herhangi bir değişiklik bulunmamaktadır. Sorun sizin kullanımınızdan kaynaklanmakta.
